# Site settings
name: 乔胜传的博客
email: qiaoshengchuan@163.com
author: LaoQiao
url: http://qiaoshengchuan.com
resume_site: http://qiaoshengchuan.com/me/
github: https://github.com/qiaoshengchuan/
baseurl: ""  #根目录
description: 假如生活欺骗了你，不要悲伤，不要哭泣。
motto: 虽叹行路难，亦做逍遥游。
banner: 我想带你去看绚丽的山峦，去看秀丽的溪谷，这份心情，人类是如何称呼的呢。
#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
excerpt_separator:  '<!-- more -->' #文章摘要
paginate: 8
paginate_path: "page:num"
plugins: [jekyll-paginate]
exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']
github_username: qiaoshengchuan
highlighter: rouge
markdown: kramdown
FB:
  comments :
    provider : disqus
    disqus :
        short_name : qiaoshengchuan
